const ALIAS_MAP = {
  'upd': 'UP Diliman',
  'up diliman': 'UP Diliman',
  'ust': 'UST',
  'ateneo': 'Ateneo',
  'dlsu': 'DLSU',
  'sm north': 'SM North EDSA',
  'sm north edsa': 'SM North EDSA',
  'moa': 'SM Mall of Asia',
  'ikot': 'UP Ikot',
  'toki': 'UP Toki',
  'katip': 'Katipunan LRT',
  'katipunan': 'Katipunan LRT',
  'cubao': 'Cubao',
  'makati': 'Makati CBD',
  'bgc': 'BGC',
  'ortigas': 'Ortigas Center',
  'pitx': 'PITX',
  'monumento': 'Monumento',
  'taft': 'Taft Avenue',
  'edsa': 'EDSA',
  'alabang': 'Alabang',
  'baclaran': 'Baclaran',
  'divisoria': 'Divisoria',
  'fairview': 'Fairview',
};

// Extended Metro Manila aliases
const EXTRA_ALIASES = {
  'kamuning': 'Kamuning',
  'kamuning edsa': 'Kamuning EDSA',
  'edsa kamuning': 'Kamuning EDSA',
  'lrt katipunan': 'Katipunan LRT Station',
  'lrt': 'LRT',
  'mrt': 'MRT',
  'anonna': 'Anonas',
  'betty go': 'Betty Go-Belmonte',
  'gilmore': 'Gilmore',
  'santolan': 'Santolan',
  'antipolo': 'Antipolo',
  'marikina': 'Marikina',
  'pasig': 'Pasig',
  'ortigas': 'Ortigas Center',
  'makati': 'Makati City',
  'cubao': 'Cubao',
  'quiapo': 'Quiapo Church',
  'divisoria': 'Divisoria Market',
  'baclaran': 'Baclaran Church',
  'alabang': 'Alabang',
  'bicutan': 'Bicutan',
  'sucat': 'Sucat',
  'pitx': 'PITX',
  'monumento': 'Monumento',
  'balintawak': 'Balintawak',
  'novaliches': 'Novaliches',
  'fairview': 'Fairview',
  'commonwealth': 'Commonwealth Avenue',
  'tandang sora': 'Tandang Sora',
  'batasan': 'Batasan Hills',
  'taft': 'Taft Avenue',
  'buendia': 'Gil Puyat Avenue',
  'ayala': 'Ayala Avenue',
  'bgc': 'BGC',
  'eastwood': 'Eastwood City',
  'trinoma': 'TriNoma',
  'glorietta': 'Glorietta',
  'greenbelt': 'Greenbelt',
  'moa': 'SM Mall of Asia',
  'sm north': 'SM North EDSA',
  'sm megamall': 'SM Megamall',
  'upd': 'UP Diliman',
  'up diliman': 'UP Diliman',
  'ust': 'UST',
  'ateneo': 'Ateneo',
  'dlsu': 'DLSU',
  'la salle': 'DLSU',
  'ikot': 'UP Ikot',
  'toki': 'UP Toki',
  'katip': 'Katipunan',
  'katipunan': 'Katipunan Avenue',
  'edsa': 'EDSA',
  'quezon ave': 'Quezon Avenue',
  'aurora blvd': 'Aurora Boulevard',
  'marcos highway': 'Marcos Highway',
  'españa': 'Espana Boulevard',
  'mendiola': 'Mendiola',
  'reclamation': 'Reclamation Area',
  'pier': 'Pier',
  'tutuban': 'Tutuban',
  'blumentritt': 'Blumentritt',
  'sta cruz': 'Sta Cruz',
  'sta mesa': 'Sta Mesa',
  'san juan': 'San Juan',
  'mandaluyong': 'Mandaluyong',
  'taguig': 'Taguig',
  'paranaque': 'Paranaque',
  'las pinas': 'Las Pinas',
  'muntinlupa': 'Muntinlupa',
  'caloocan': 'Caloocan',
  'malabon': 'Malabon',
  'navotas': 'Navotas',
  'valenzuela': 'Valenzuela',
  'meycauayan': 'Meycauayan',
  'marilao': 'Marilao',
  'bocaue': 'Bocaue',
  'san mateo': 'San Mateo',
  'rodriguez': 'Rodriguez',
  'antipolo': 'Antipolo',
  'taytay': 'Taytay',
  'cainta': 'Cainta',
  'binangonan': 'Binangonan',
  'angono': 'Angono',
};

// Merge into ALIAS_MAP
for (const [k, v] of Object.entries(EXTRA_ALIASES)) {
  if (!ALIAS_MAP[k]) ALIAS_MAP[k] = v;
}

const RELATIVE_ORIGIN_RE = /\b(here|dito|nandito|my location|current location|where i am|near me)\b/i;

export function normalizeQuery(text, location) {
  let normalized = text.trim();
  normalized = normalized.replace(RELATIVE_ORIGIN_RE, 'here');
  for (const [alias, expansion] of Object.entries(ALIAS_MAP)) {
    const escaped = alias.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const re = new RegExp('\\b' + escaped + '\\b', 'gi');
    normalized = normalized.replace(re, expansion);
  }
  return { normalized, usedLocation: RELATIVE_ORIGIN_RE.test(text) };
}
